doctrine:
   dbal:
       default_connection: pgsql
       connections:      
       pgsql:
            driver: pdo_pgsql
            host: "127.0.0.1"
            port: "5432"
            dbname: "postgres-db"
            user: "root"
            password: "root"
            charset: UTF8

       orm:
          auto_generate_proxy_classes: "%kernel.debug%"
          naming_strategy: doctrine.orm.naming_strategy.underscore
          auto_mapping: true
                                                                                                                              
