register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\AuthController::api

login_check:
    path: /login_check
    methods: [POST]

address:
    path: /address
    controller: App\Controller\AddressController::Address
    methods: [GET]

city:
    path: /city
    controller: App\Controller\CityController::City
    methods: [GET]

cinema_theater:
    path: /cinema_theater
    controller: App\Controller\Cinema_TheaterController::Cinema_Theater
    methods: [GET]




